### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [tibbdc/ECMpy#2]
The example Juypter notebooks don't run any more with current cobrapy. For instance, the "add_reaction" function has been removed. Now, there is only "add_reactions". Perhaps you can update the code or fix the last cobra version where it worked.

**Comment by maozhitao** [comment]
Thank you for your attention. The updated version of ECMpy is available at https://github.com/tibbdc/ECMpy2.0, which includes automated model construction and various analysis functionalities.

**Comment by VonAlphaBisZulu** [comment]
Great thank you. Since the problem persists in ECMpy2.0, I have created a similar issue and pull request, there.
