### ISSUE TITLE
[Documentation] Refer to ECMpy2.0

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [tibbdc/ECMpy#4]
Please add a first line in the readme and let potential users know that the package is deprecated / has been replaced by ECMpy2.0.

**Comment by maozhitao** [comment]
Thank you very much for your suggestions. After careful consideration, we have decided to close the ECMpy 2.0 project and instead release version 2.0.0 within the existing ECMpy project. We have reopened the issue you raised and provided relevant responses to address the concerns.
