### ISSUE TITLE
BRENDA file not available anymore

### ISSUE THREAD

**Issue by mheydasch** [tibbdc/ECMpy#8]
https://www.brenda-enzymes.org/brenda_download/file_download.php does not exist anymore, leading to FileNotFoundError: [Errno 2] No such file or directory: './data/brenda_2023_1.txt

 I assume what is the correct file can now be found under https://www.brenda-enzymes.org/download.php

**Comment by maozhitao** [comment]
You are correct in assuming that the correct file can now likely be found on the new download page at https://www.brenda-enzymes.org/download.php.
